const UnityTypes = [
  "Genel",
  "Cumhuriyet Başsavcılığı",
  "Ağır Ceza Mahkemesi",
  "Ceza Mahkemeleri Ön Bürosu",
  "Asliye Ceza Mahkemesi",
  "Aile Mahkemesi",
  "Çocuk Mahkemesi",
  "İnfaz Hakimliği",
  "Sulh Ceza Hakimliği",
  "İcra Mahkemesi",
  "Asliye Hukuk Mahkemesi",
  "İş Mahkemesi",
  "Sulh Hukuk Mahkemesi",
  "Hukuk Mahkemeleri Ön Bürosu",
  "Arabuluculuk Bürosu",
  "Adlî Yargı İlk Derece Mahkemesi Adalet Komisyonu Başkanlığı",
  "İcra Dairesi",
  "İcra Tevzi Bürosu",
  "Mahkemeler Veznesi",
  "Tarama Merkezi",
  "Hukuk Mahkemeleri Tevzi Bürosu",
  "Tüketici Mahkemesi",
  "Kadastro Mahkemesi",
  "Açık Ceza İnfaz Kurumu",
  "Kapalı Ceza İnfaz Kurumu",
];

exports.UnityTypes = UnityTypes;
